version: "1.1"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: t2410e_spring
      MYSQL_USER: t2410e
      MYSQL_PASSWORD: t2410e_password
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:7.2
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
volumes:
  mysql_data:
  redis_data: