spring.application.name=t2410e
spring.datasource.url=jdbc:mysql://localhost:3308/t2410e_spring
spring.datasource.username=t2410e
spring.datasource.password=t2410e_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect




